import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { apiFetch } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { formatBeijingDateTime } from '@/lib/utils'

type Order = { id: number; order_no: string; user_id: number; email: string; amount: number; status: string; payment_method: string | null; provider_trade_no: string | null; note: string | null; created_at: string; paid_at: string | null }
const statuses = [['', '全部'], ['pending', '待支付'], ['paid', '已到账'], ['cancelled', '已取消'], ['expired', '已过期']]
const labels: Record<string, string> = { pending: '待支付', paid: '已到账', cancelled: '已取消', expired: '已过期' }
function date(value: string | null) { return value ? formatBeijingDateTime(value) : '-' }
function money(value: number) { return `$${Number(value || 0).toFixed(2)}` }

export default function AdminRechargePage() {
  const client = useQueryClient(); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [selected, setSelected] = useState<Order | null>(null); const [tradeNo, setTradeNo] = useState(''); const [note, setNote] = useState(''); const [message, setMessage] = useState('')
  const orders = useQuery<{ orders: Order[] }>({ queryKey: ['admin-recharge-orders', search, status], queryFn: () => apiFetch(`/api/admin/recharge/orders?q=${encodeURIComponent(search)}&status=${encodeURIComponent(status)}`) })
  const groupedOrders = useMemo(() => { const groups = new Map<string, Order[]>(); for (const order of orders.data?.orders ?? []) groups.set(order.email, [...(groups.get(order.email) ?? []), order]); return Array.from(groups, ([email, items]) => ({ email, items })) }, [orders.data?.orders])
  const markPaid = useMutation<{ balance_after?: number; balance?: number }, Error, Order>({ mutationFn: (order) => apiFetch(`/api/admin/recharge/orders/${order.id}/mark-paid`, { method: 'POST', body: JSON.stringify({ provider_trade_no: tradeNo.trim() || undefined, note: note.trim() || undefined }) }), onSuccess: (data) => { setSelected(null); setTradeNo(''); setNote(''); setMessage(`到账成功，用户新余额：${money(data.balance_after ?? data.balance ?? 0)}`); client.invalidateQueries({ queryKey: ['admin-recharge-orders'] }); client.invalidateQueries({ queryKey: ['admin-users'] }); client.invalidateQueries({ queryKey: ['admin-wallet-users'] }) } })
  function confirm(order: Order) { if (!window.confirm('确认该充值订单已实际收到款项吗？确认后将立即增加用户余额。')) return; setSelected(order) }
  return <div className="max-w-[1700px]"><h1 className="text-xl font-semibold">充值订单</h1><p className="mt-1 text-sm text-muted-foreground">按用户邮箱归纳查看充值记录。</p><div className="mt-5 flex flex-wrap gap-3"><Input className="max-w-sm" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="搜索订单号或用户邮箱" /><select className="h-8 rounded-lg border border-input bg-background/95 px-3 text-sm text-foreground" style={{ colorScheme: 'dark' }} value={status} onChange={(e) => setStatus(e.target.value)}>{statuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{message && <div className="mt-4 rounded-xl border p-3 text-sm">{message}</div>}{selected && <div className="mt-5 max-w-xl rounded-2xl border bg-muted/20 p-4"><h2 className="font-medium">确认到账：{selected.order_no}</h2><p className="mt-1 text-sm">金额 {money(selected.amount)}，用户 {selected.email}</p><div className="mt-4"><label className="text-xs">交易号（可选）</label><Input className="mt-1.5" value={tradeNo} onChange={(e) => setTradeNo(e.target.value)} /></div><div className="mt-3"><label className="text-xs">备注（可选）</label><Textarea className="mt-1.5" value={note} onChange={(e) => setNote(e.target.value)} /></div><div className="mt-4 flex gap-2"><Button disabled={markPaid.isPending} onClick={() => markPaid.mutate(selected)}>{markPaid.isPending ? '处理中…' : '确认到账'}</Button><Button variant="outline" onClick={() => setSelected(null)}>取消</Button></div>{markPaid.isError && <p className="mt-3 text-sm text-destructive">{markPaid.error.message}</p>}</div>}
  <div className="mt-6 grid gap-4 md:grid-cols-2">{groupedOrders.map((group) => <details key={group.email} className="group relative h-fit rounded-2xl border bg-card p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4"><div className="min-w-0"><div className="truncate text-sm font-medium">{group.email}</div><div className="mt-1 text-xs text-muted-foreground">{group.items.length} 条充值记录</div></div><div className="flex shrink-0 items-center gap-3"><span>{money(group.items.reduce((sum, order) => sum + order.amount, 0))}</span><span className="rounded-full border px-2 py-1 text-xs">展开查看</span><span className="text-muted-foreground transition-transform group-open:rotate-180">⌄</span></div></summary><div className="absolute left-0 right-0 top-full z-30 mt-2 rounded-2xl border border-border/80 bg-background/95 p-5 shadow-2xl backdrop-blur-xl"><div className="space-y-2">{group.items.map((order) => <details key={order.id} className="group/order rounded-xl border p-3"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-sm"><span className="truncate font-mono text-xs">{order.order_no}</span><span>{money(order.amount)}</span><span className="rounded-full border px-2 py-1 text-xs">{labels[order.status] ?? order.status}</span></summary><div className="mt-3 grid gap-3 border-t pt-3 text-xs sm:grid-cols-2"><div><span className="text-muted-foreground">用户 ID</span><div className="mt-1">{order.user_id}</div></div><div><span className="text-muted-foreground">支付方式</span><div className="mt-1">{order.payment_method ?? '支付宝'}</div></div><div><span className="text-muted-foreground">创建时间</span><div className="mt-1">{date(order.created_at)}</div></div><div><span className="text-muted-foreground">支付时间</span><div className="mt-1">{date(order.paid_at)}</div></div><div><span className="text-muted-foreground">第三方交易号</span><div className="mt-1 break-all">{order.provider_trade_no ?? '-'}</div></div><div><span className="text-muted-foreground">备注</span><div className="mt-1 break-all">{order.note ?? '-'}</div></div></div>{order.status === 'pending' && <Button className="mt-4" size="sm" onClick={() => confirm(order)}>确认到账</Button>}</details>)}</div></div></details>)}</div>{!orders.isLoading && groupedOrders.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">暂无充值订单。</p>}</div>
}
