import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { apiFetch } from '@/lib/api'
import { formatBeijingDateTime } from '@/lib/utils'

type Data = { users: { total: number; enabled: number }; keys: { total: number; active: number }; stats: { requests: number; success: number; failures: number; input: number; output: number; successRate: number; revenue: number }; wallet: { balance: number; reserved: number }; recharge: { total: number }; models: Array<{ platform: string; model: string; requests: number; tokens: number; revenue: number }>; providers: Array<{ platform: string; requests: number; success_rate: number }>; failures: Array<{ created_at: string; email: string | null; model: string; platform: string; error: string }> }
const money = (micro: number) => `$${(Number(micro || 0) / 1_000_000).toFixed(2)}`
const number = (value: number) => new Intl.NumberFormat('zh-CN').format(Number(value || 0))
const percent = (value: number) => `${Number(value || 0).toFixed(2).replace(/\.00$/, '').replace(/(\.\d)0$/, '$1')}%`

function Card({ label, value, hint, tone = 'default' }: { label: string; value: string | number; hint?: string; tone?: 'default' | 'green' | 'red' }) {
  return <div className="rounded-2xl border bg-card p-4"><div className="text-xs text-muted-foreground">{label}</div><div className={`mt-2 text-2xl font-semibold tabular-nums ${tone === 'green' ? 'text-emerald-500' : tone === 'red' ? 'text-destructive' : ''}`}>{value}</div>{hint && <div className="mt-1 text-xs text-muted-foreground">{hint}</div>}</div>
}

export default function AdminDashboardPage() {
  const [range, setRange] = useState('30d')
  const { data, isLoading } = useQuery<Data>({ queryKey: ['admin-dashboard', range], queryFn: () => apiFetch(`/api/admin/dashboard/summary?range=${range}`), refetchInterval: 5000 })
  const s = data?.stats
  const maxModelRequests = Math.max(...(data?.models.map(m => m.requests) ?? [1]), 1)
  const maxProviderRequests = Math.max(...(data?.providers.map(p => p.requests) ?? [1]), 1)
  const successRate = s?.successRate ?? 0
  return <div className="max-w-7xl space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">管理员仪表盘</h1><p className="mt-1 text-sm text-muted-foreground">全站用户、模型、请求与收入的实时统计。</p></div><select className="h-9 rounded-xl border bg-transparent px-3 text-sm" value={range} onChange={e => setRange(e.target.value)}><option value="today">今天</option><option value="7d">最近 7 天</option><option value="30d">最近 30 天</option><option value="all">全部时间</option></select></div>
    {isLoading ? <div className="rounded-3xl border p-12 text-center text-sm text-muted-foreground">正在加载全站数据…</div> : <>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-6"><Card label="用户总数" value={number(data?.users.total ?? 0)} hint={`已启用 ${number(data?.users.enabled ?? 0)}`} /><Card label="API 密钥" value={number(data?.keys.total ?? 0)} hint={`活跃 ${number(data?.keys.active ?? 0)}`} /><Card label="总请求数" value={number(s?.requests ?? 0)} /><Card label="成功率" value={percent(successRate)} tone="green" /><Card label="输入 Token" value={number(s?.input ?? 0)} /><Card label="输出 Token" value={number(s?.output ?? 0)} /></div>
      <div className="grid gap-6 lg:grid-cols-3"><div className="rounded-3xl border bg-card p-5 lg:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-medium">请求与模型排行</h2><p className="mt-1 text-xs text-muted-foreground">全站模型调用次数及 Token 使用量</p></div><span className="text-xs text-muted-foreground">实时更新</span></div><div className="mt-5 space-y-4">{data?.models.slice(0, 8).map(m => <div key={`${m.platform}-${m.model}`}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate">{m.model}</span><span className="shrink-0 tabular-nums text-muted-foreground">{number(m.requests)} 次 · {number(m.tokens)} Token</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-foreground transition-all" style={{ width: `${Math.max(3, m.requests / maxModelRequests * 100)}%` }} /></div></div>)}{!data?.models.length && <p className="py-8 text-center text-sm text-muted-foreground">暂无模型请求数据</p>}</div></div><div className="rounded-3xl border bg-card p-5"><h2 className="font-medium">全站成功率</h2><p className="mt-1 text-xs text-muted-foreground">成功与失败请求占比</p><div className="mx-auto mt-6 grid size-44 place-items-center rounded-full" style={{ background: `conic-gradient(#10b981 ${successRate}%, hsl(var(--muted)) 0)` }}><div className="grid size-32 place-items-center rounded-full bg-card"><div className="text-center"><div className="text-3xl font-semibold">{percent(successRate)}</div><div className="text-xs text-muted-foreground">成功率</div></div></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><div className="text-muted-foreground">成功</div><div className="mt-1 font-semibold text-emerald-500">{number(s?.success ?? 0)}</div></div><div><div className="text-muted-foreground">失败</div><div className="mt-1 font-semibold text-destructive">{number(s?.failures ?? 0)}</div></div></div></div></div>
      <div className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border bg-card p-5"><h2 className="font-medium">供应商请求分布</h2><div className="mt-5 space-y-4">{data?.providers.map(p => <div key={p.platform}><div className="mb-1 flex justify-between text-sm"><span>{p.platform}</span><span className="text-muted-foreground">{number(p.requests)} 次 · 成功率 {percent(p.success_rate)}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-[var(--series-a)]" style={{ width: `${Math.max(3, p.requests / maxProviderRequests * 100)}%` }} /></div></div>)}</div></div><div className="rounded-3xl border bg-card p-5"><h2 className="font-medium">资金概览</h2><div className="mt-5 grid grid-cols-2 gap-3"><Card label="累计收入" value={money(s?.revenue ?? 0)} /><Card label="充值到账" value={money(data?.recharge.total ?? 0)} /><Card label="用户总余额" value={money(data?.wallet.balance ?? 0)} /><Card label="冻结余额" value={money(data?.wallet.reserved ?? 0)} /></div></div></div>
      <div className="rounded-3xl border bg-card p-5"><h2 className="font-medium">最近失败请求</h2>{data?.failures.length ? <div className="mt-4 divide-y">{data.failures.slice(0, 8).map((f, i) => <div key={i} className="grid gap-1 py-3 text-sm md:grid-cols-[180px_1fr_auto]"><span className="text-xs text-muted-foreground">{formatBeijingDateTime(f.created_at)}</span><span>{f.email ?? '系统'} · {f.model} · {f.platform}<div className="mt-1 text-xs text-destructive">{f.error || '请求失败'}</div></span><span className="text-xs text-muted-foreground">失败</span></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">暂无失败请求</p>}</div>
    </>}
  </div>
}
