import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { apiFetch } from '@/lib/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
type Key = { id: number; name: string; keyPrefix: string; status: string; enabled: 0 | 1; requestCount: number; inputTokens: number; outputTokens: number; createdAt: string; lastUsedAt: string | null; expiresAt: string | null }
export default function UserApiKeysPage() {
  const client = useQueryClient(), [name, setName] = useState(''), [error, setError] = useState(''), [newKey, setNewKey] = useState('')
  const keys = useQuery<{ keys: Key[] }>({ queryKey: ['consumer-keys'], queryFn: () => apiFetch('/api/consumer-keys') })
  const create = useMutation<{ key: string }>({ mutationFn: () => apiFetch('/api/consumer-keys', { method: 'POST', body: JSON.stringify({ name: name.trim(), expiration: 'never' }) }), onSuccess: response => { setName(''); setNewKey(response.key); client.invalidateQueries({ queryKey: ['consumer-keys'] }) } })
  const toggle = useMutation({ mutationFn: (key: Key) => apiFetch(`/api/consumer-keys/${key.id}`, { method: 'PATCH', body: JSON.stringify({ enabled: !key.enabled }) }), onSuccess: () => client.invalidateQueries({ queryKey: ['consumer-keys'] }) })
  const revoke = useMutation({ mutationFn: (id: number) => apiFetch(`/api/consumer-keys/${id}`, { method: 'DELETE' }), onSuccess: () => client.invalidateQueries({ queryKey: ['consumer-keys'] }) })
  const baseUrl = `${window.location.origin}/v1`
  return <div className="rounded-3xl border bg-card p-6"><h1 className="text-2xl font-semibold">API 密钥</h1><div className="mt-5 flex gap-2"><Input value={name} onChange={e => setName(e.target.value)} placeholder="API 密钥名称" /><Button disabled={create.isPending} onClick={() => { if (!name.trim()) { setError('请输入 API 密钥名称。'); return } setError(''); setNewKey(''); create.mutate() }}>{create.isPending ? '创建中…' : '创建 API 密钥'}</Button></div>{error && <p className="mt-2 text-sm text-destructive">{error}</p>}{newKey && <div className="mt-4 rounded-2xl border bg-muted/30 p-4"><p className="font-medium">新创建的 API 密钥</p><p className="mt-1 text-xs text-muted-foreground">完整 API 密钥只会显示一次，请立即复制保存。</p><code className="mt-3 block break-all rounded-lg border bg-background p-3">{newKey}</code><div className="mt-4 text-sm"><div className="text-xs text-muted-foreground">Base URL</div><code className="mt-1 block break-all rounded-lg border bg-background p-3">{baseUrl}</code></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => navigator.clipboard.writeText(newKey)}>复制 API 密钥</Button><Button size="sm" variant="outline" onClick={() => navigator.clipboard.writeText(baseUrl)}>复制 Base URL</Button></div></div>}<div className="mt-6 space-y-3">{keys.data?.keys.map(key => <div key={key.id} className="rounded-2xl border p-4 text-sm"><div className="flex flex-wrap justify-between gap-2"><span className="font-medium">{key.name}</span><code>{key.keyPrefix}...</code><span>{key.status === 'revoked' ? '已撤销' : key.enabled ? '启用' : '已暂停'}</span></div><div className="mt-3 grid gap-2 text-xs text-muted-foreground sm:grid-cols-2 lg:grid-cols-4"><span>请求数：{key.requestCount}</span><span>Token：{key.inputTokens + key.outputTokens}</span><span>创建时间：{new Date(key.createdAt).toLocaleString()}</span><span>最后使用：{key.lastUsedAt ? new Date(key.lastUsedAt).toLocaleString() : '从未使用'}</span><span>过期时间：{key.expiresAt ? new Date(key.expiresAt).toLocaleString() : '永不过期'}</span></div><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" onClick={() => toggle.mutate(key)} disabled={key.status === 'revoked'}>{key.enabled ? '暂停' : '恢复'}</Button><Button size="sm" variant="outline" onClick={() => revoke.mutate(key.id)} disabled={key.status === 'revoked'}>撤销</Button></div></div>)}</div></div>
}
